import Image from "next/image";

const AboutSectionThree = () => {
  return (
    <section className="py-16 md:py-20 lg:py-28">
      <div className="container">
          <div className="w-full px-4 ">
            <div className="max-w">
              <div className="mb-9">
                <h3 className="mb-4 text-xl font-bold text-black dark:text-white sm:text-2xl lg:text-xl xl:text-2xl">
                  Our History
                </h3>
                <p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The Beginnings, 1999 - 2000</p><p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed"> <br></br>Appropriately, the NPTE began in a debate van on the way home from the 1999 Ohio State debate tournament. Creighton’s Jason Steck, Adam Astley, Jon Lang, and coach Marty Birkholt contemplated the lack of a parliamentary debate tournament that focused on year-long performance. Jason and Marty began to devise and refine elaborate mathematical formulas for how to measure tournament strength and team performance. Adam whipped out his ever-present Powerbook G4 and began to sketch some ideas for an automated online ranking system. Jon got so excited that he took a wrong turn and headed for Memphis.
<br></br>
Three months later, Whitman’s Jim Hanson and Wyoming’s Matt Stannard went to lunch in the midst of the 2000 NPDA National tournament and began to outline their own vision for a national championship based on a qualification system. Teams would earn their way towards bids based on a series of invitational tournaments over the course of an entire year. Judges would be screened for qualifications. The combination of the top debate teams in the country and the best judges would produce a tournament style unique in parliamentary debate.
<br></br>
These threads came together in the summer of 2000, as Michelin Massey from the University of Colorado put out a public call for interested parties to come together to discuss the creation of a qualification-based national parliamentary debate tournament. The parlitoc mailing list served as the forum for discussion as, over the course of June and July, the details of the ranking system discussed by debaters on the way home from Ohio merged with the vision provided by experienced coaches.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">A Small Start, 2001</p><p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">In April of 2001, the first NPTE President (then called Chair), Matt Stannard from the University of Wyoming, welcomed 13 teams to the first NPTE in Walla Walla, Washington. While the tournament was small, the competition was grueling. Debaters at the 2001 NPTE were the first to make the comment that was to become the routine description of the NPTE tournament experience – every round is like an out-round. In the first-ever division of the house with ballots submitted by NPTE participants including both judges and competitors, the University of Oregon FT (Heidi Ford and Alan Tauber) defeated the Air Force Academy MR (Amanda Myers and Chad Richards) on a 12-7 vote. The top speaker was Air Force’s Amanda Myers.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The NPTE Takes Off, 2002</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">From this humble beginning, the NPTE took off like a rocket, driven by the enthusiasm of debaters who competed to attain higher ranks on the NPTE online ranking list. By March of 2002, when new NPTE President Jim Hanson from Whitman College opened the second NPTE at Regis University, the tournament was already filled to its maximum size of 36 teams and the competition was correspondingly fierce. In a well-attended final round, California State University at Long Beach CM (Kristine Clancy and Audrey Mink) prevailed over Northern Arizona University SW (Danny Shea and Brandon Whearty) on a close 31-24 decision, producing the first all-female national champion team in American parliamentary debate. Michael Owens of the University of Wyoming claimed first place individual honors.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2003</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">36 teams and full use of double judging: Enthusiasm among debaters and coaches continued to grow over the next year, as the NPTE became broadly recognized as a premier national championship for parliamentary debate. In March of 2003, Lewis and Clark College hosted the third annual NPTE which included a full suite of 36 teams and a full group of 41 judges, allowing for the full use of the NPTE’s unique 2-judge format in preliminary rounds. In front of a packed gallery, the University of Wyoming OW (Michael Owens and Josh Wilkerson) put the finishing touches on an unbelievable 12-0 preliminary round record by defeating California State University at Long Beach on a 57-9 division of the house. Piling the fantastic atop the unbelievable, Michael Owens renewed his claim on the top speaker award for a second straight year.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2004</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">48 Teams: Acknowledging the growing national scope of the NPTE, the Board voted in the summer of 2003 to expand the maximum tournament size to 48 teams and to accept results from a much larger number of tournaments. The results were impressive, with a full 2004 NPTE and an intense, nationwide competition for NPTE bids. This year’s NPTE champion navigated a difficult field, truly demonstrating excellence in parliamentary debate. South Carolina, Glenn Prince and J.D. Shipman, defeated Whitman College, Scott Thompson and Chris Gorman, in the finals round held at the University of California at Berkeley.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2005</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">36 teams: The NPTE was held at Century College. In finals, South Carolina, Ian Samuel and Marie Tenny, defeated Colorado State, Matthew Plush and Adam Sirimarco. This year, the board adjusted the bonus tournaments to gradations of .1 up to 1 point for non-regional teams and up to 1 point for number of teams above 20 in a division. Changes to eligibility and certification of attendance in courses were established. This is the year that the board also transitioned from a listserv to a web based bulletin board.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2006</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">36 teams: The board made multiple tweaks to the NPTE system including eligibility requirements, adjustments to the points system, and even a new partial double elimination procedure with 6-6 and better teams advancing (something that produced an outcry and was rescinded before being used), and Gary Larson wrote a special version of his tab room program for the NPTE—making the elimination rounds day an hour shorter. Konrad Hack handled tab room duties. We also switched from an ABCX preference system to an ABCDEX preference system. We ended the districts as the point system seemed to be assuring enough diversity in regional representation. Held at the University of Oregon, Josh Anderson and Rachel Safran from the University of Puget Sound defeated Loyola Marymount (Contreras/Mumper).<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2007</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">56 teams: The NPTE board expanded the tournament to permit up to 56 teams to compete. This was done to avoid problems with having teams receive byes during the quarters/final double elimination round. Additionally, the board adjusted the eligibility requirements, added opportunity bids for teams unable to acquire NPTE points due to hardship, the board moved the deadline for first rounds to mid January, mutual preference judging was tweaked having larger ABCD categories. We also began permitting fourth teams from a squad. Held at the University of Wyoming, Kevin Garner and Luke Landry from William Jewell defeated Thomas Brugato and Ryan Lawrence from UC Berkeley.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2008</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">54 teams: Only a minor change was made to the tournament; to reduce the chance that a runoff round would occur, the tournament permitted only 54 teams to compete. Transfer rules were changed to avoid problems the board faced the previous year and a new time limit on how long judges could take before ballots were turned in was instituted. Held at the University of Puget Sound. Southern Illinois Kevin Calderwood and Kyle Dennis defeated Washburn University, Annaleigh Curtis and Marcus-Schultz-Bergin, in finals. The tournament was marked by a few unfortunate tab errors and calls for democratization of the NPTE, some constructive, others angry and heated.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">2009</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">64 Teams: Following the contentious 2008 NPTE, the NPTE board made major changes. The final round became judged by a panel of critics rather than all those in attendance. The tournament was changed to 64 teams that would break to what new board member Konrad Hack called the golden number 32 with double elims all the way through finals. Further, the tournament was changed from 2 to 3 days in length. Topic areas became controversy areas, more specific and focused with an actor, action, and direction specified. Treasurer and Executive Secretary positions were added to the board bringing the board to 7 members. Further, the NPTE added memberships for schools for more direct input into decisions including veto power over board decisions. Minor changes were made to the points system. Tournament results were accepted one week later than previously. Seeding procedures were changed. Further, in elims, teams were now given the option to not debate against each other. Finally, President Jim Hanson, who had wanted to step down as President prior to the business meeting, stayed on for 3 months of intense discussion and votes on the many changes made to the NPTE as a replacement initially could not be found. Derek Buescher became that replacement when he was chosen as a new board member who would become the President for the 2009-2010 year which he did at the end of the business meetings held in May, June and July. Glenn Prince served as Executive Secretary until January when Joe Gantt took on the job. The 2009 NPTE was held at UC-Berkeley and was won by The University of Nevada Reno (Max Alderman and David Pena) over Southern Illinois University (Kevin Calderwood and Adam Testerman) on a 4-3 decision (the first judging panel rather than audience judged final).<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2010 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">64 teams: Held at Azusa Pacific, the NPTE followed a relatively calm year with almost exclusively minor changes made to the tournament. Joe Gantt established a new win-loss-quality of opponent scoring system for tie breakers at the tournament. Announcement of sides and topics as a group for elims was adopted as the standard procedure (although it had already been used). Clubs were allowed to compete at the NPTE. The Vice President position officially took over the topic writing process and initiated topic papers. The NPTE Rules were reorganized into 3 documents: one for the board, one for the qualifying procedures, and one for the tournament procedures. The University of Colorado at Boulder (Than Hedman & Will Van Treuren) defeated the University of Oregon (Matt Gander & Hank Fields) on a 7-0 decision.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2011 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">64 teams: Held at the University of Denver, the NPTE continued the relative calm. The business meeting discussed a few items but mainly only agreed to clarify and tweak eligibility requirements and then in February, the board dealt with a fairly complicated issue involving whether a hybrid would be allowed to compete at the tournament (which the board did allow). The University of Oregon (Matt Gander and Hank Fields) defeated Whitman College (Nigel Ramoz-Leslie and Tom Friedenbach) on a 7-0 decision. At the tournament, Jason Steck and Patty Steck announced the end of their long time service to the NPTE.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2012 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">64 teams: Held at Western Washington University, the NPTE dealt with minor changes over the 2011 spring and summer as the business meeting extended into early September. On a close vote, hybrids were no longer allowed at the NPTE. Some of the President’s duties regarding the tournament were handed over to the Treasurer, Jim Hanson, including the sending of invitations. Controversy areas were reduced to 4 for the tournament to reduce the research burden on teams. Jim Hanson reviewed the NPTE rules in an attempt to clean up items that were not clear to reduce ambiguity. Left unchanged but the cause of a great deal of discussion on the board was the phenomenon of swing tournaments where two point counting tournaments happened during one weekend; some argued that the tournaments had too few rounds each to be good ways of establishing elimination round seedings while also creating long weekends (20+ debates) while others argued that the tournaments seeded just fine and gave an important bang for the buck by providing 2 tournaments for the cost of nearly just 1 tournament.<br></br>

At the tournament itself, the board had its first face to face full meeting with new President Joe Blasdel leading. The board discussed changes to positions on the board, .1 increment speaker points, ordinal mutual preferencing, too many topics (4 topic areas times 6 resolutions was considered too many) and changes to the topic areas, as well as swings and the NPTE point structure. Washburn University (Josh Ramsey and Lauren Knoth) defeated Texas Tech University (Adam Testerman and Joey Donaghy) on a 5-2 decision.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2013 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">56 teams: Held at the University of Nevada at Reno, the NPTE made major changes as the business meeting extended into the fall and even early spring. Bids were now offered to teams that earned at least 18 points rather than establishing a 64 team cap. Points were changed with additional points given to tournaments with more rounds; no bonus points for tournaments with teams from 400+ miles away; teams counted only their top 4 tournaments and teams attending more than 10 tournaments had their points reduced unless they opted to not count tournaments. Controversy areas were reduced to 3 for the tournament and the tournament pre-announced which of the topics would be used during the first 8 rounds of competition. The goal was to reduce the research burden on teams. At the tournament itself, things went smoothly. Southern Illinois University (Mike Selck and Josh Rivera) defeated Whitman College (Miranda Morton and Mitch Dunn) on a 4-3 decision.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2014 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">56 teams: Held at Northern Arizona University at Flagstaff, Arizona, the NPTE made mostly minor tweaks before the tournament occurred including expanding the opportunity bids, a slight adjustment to counting of points, reduced numbers of resolutions from 24 down to 18, and new guidelines for judges and students to create a good environment at the tournament. Tech problems with assigning resolution and sides in elims delayed the tournament on day two; day three went smoothly after the problems were ironed out. The board had a healthy set of discussions about changes for the 2015 NPTE—identifying over 15 items for action, some of which were significant: reducing resolutions to 6 to 8; ending the two resolutions per elimination round, reducing strikes and altering judge preference judging to emphasize mutuality more. Lewis and Clark College (Emily Halter and McKay Campbell) defeated Whitman College (Marten King and Logan Emlet) on a 4-3 decision.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2015 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">68 teams: The largest NPTE yet, the 2015 tournament was held at William Jewell College at Liberty, Missouri (near Kansas City). The NPTE board reduced the number of topics to 15 and ended the two topics for each elimination round. An internet problem slowed the first round and then an appeal after the first round led in total to a 3 hour delay during the first day of competition. An innovative feature of the tournament was to change judge preferencing so that it was more attuned to mutuality and to prioritizing the placement of some judges. The result is that women and men judges were used equally during the preliminary rounds while preference levels for the teams remained fairly high; the board needs to do more work for the elimination rounds. The board dealt with multiple issues arising from in round arguments that often took on a personal tone as students argued against sexism, racism, and for greater social justice. Southern Illinois University (Josh Rivera and Zach Schneider) defeated the University of Texas-Tyler (Sam Cook and Steven Hullum) on a 6-1 decision in the final round.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2016 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">54 teams: The NPTE shrunk and was held at El Camino College in Torrance, California (larger Los Angeles). The NPTE board made mostly minor changes including ending opportunity bids, adjusting preferencing in the elimination rounds to assure more diversity of judging while maintaining preferences and mutuality. The tournament did not have any significant delays but rounds took time and so the schedule was off 30 to 60 minutes each day but as a whole, the tournament ran very smoothly. The board worked further on issues in how people treat each other in and out of the rounds. The University of Texas-Tyler (Sam Cook and Steven Hullum) defeated Washburn (Kaitlyn Bull and Ryan Kelly) on a 6-1 decision in the final round.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2017 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">50 teams: The NPTE was held at Colorado State University-Pueblo in Pueblo, CO. The NPTE Board sought minor changes for the competitive year to ensure the elimination round procedure worked effectively for a smaller pool of teams. In the final round, Washburn University (Kaitlyn Bull & Ryan Kelly) defeated Parliamentary Debate at Berkeley (Thomas Liao and Tom Kadie) on 5-2 decision, debating the topic, The United Nations should substantially increase its water assistance program to the people in the Syrian Arab Republic. At the conclusion of the NPTE, Kathryn Starkey of CSU-Pueblo was named the NPTE President. Once elected, she helped create a democratic process for the election of all new board members, which began with the election of new at-large board member, Jason Jordan of the University of Utah.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2018 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">42 teams: The 2018 tournament was held at Lewis & Clark College in Portland, OR. This year, despite lower overall attendance, the NPTE had four new schools represented: Grand Canyon University, Transylvania University, University of California Santa Barbara, and University of Minnesota. At the end of the tournament, Parliamentary Debate at Berkeley defeated Mercer University on a 4-3 decision on the topic The United States federal government should significantly increase its ballistic missile submarine fleet. In addition to crowning the champion at the awards ceremony, the NPTE announced four new community awards to honor those that are dedicated to the activity. This year, Lauran Schaefer (William Jewell College) received the Inclusion & Equity Award; Zach Schneider (McKendree University) was awarded the Service Award; Amanda Ozaki-Laughon (Concordia University-Irvine) was named the Director of Debate of the year; and Adam Testerman (Texas Tech University) was named Director of Forensics of the year. The NPTE board also underwent a big transition. 3 Board Member seats were up for election, which led to Kyle Dennis, Ashley Nuckels-Cuevas, and Zach Schneider being elected to the Board.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2019 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">26 teams: The 2019 NPTE returned to the University of Nevada, Reno. The board enacted a set of rules changes at the beginning of the season to increase the difficulty of qualifying to the NPTE. These changes ensured that the NPTE continues to fulfill its mission as a tournament with challenging competition among only the best teams in the country. Accordingly, fewer teams qualified to the NPTE and only 16 teams cleared to elimination rounds. Additionally, the topic process was changed such that the tournament has only five community-selected topics; the topics are reused in elimination rounds, with one team selecting the topic for the debate and the other team selecting the sides. In the final round, Parli Debate at Berkeley (Henry Tolchard & Tom Kadie) defeated Rice University (Jason Barton & Sonia Torres) on a 7-0 decision, debating the topic: The United States federal government should significantly decrease its military presence in one of the following: Republic of Korea, Republic of China, Okinawa Prefecture. David Worth (Rice University) was named Coach of the Year, while Trevor Greenan (Parli Debate at Berkeley) was named the top preferred critic.<br></br></p>

<br></br><p className="text-base font-medium leading-relaxed sm:text-lg sm:leading-relaxed">The 2020 NPTE</p> <p className="text-base font-medium leading-relaxed text-body-color sm:text-lg sm:leading-relaxed">28 teams: The 2020 NPTE was held at McKendree University in Lebanon, IL. It continued the 2019 trend of a smaller, more competitive tournament, with only the top 16 teams clearing to elimination rounds. In the final round, Parli Debate at Berkeley (Amanda Miskell & Brian Yang) defeated the University of Texas at Tyler (Ayush Kumar & Mason Remaley) on a 4-3 decision, debating the topic: The United States federal government should significantly increase its financial incentives for energy production in the United States from one or more of the following sources: nuclear power, solar power, wind power. Brent Nicholson (McKendree University) was named Coach of the Year, and Trevor Greenan (Parli Debate at Berkeley) was named the top preferred critic for the second consecutive year.</p>

              </div>
            </div>
          </div>
          </div>
    </section>
  );
};

export default AboutSectionThree;